# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Hello World

on:
  push:
    branches: [job]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: 인사
        run: echo "Hello, GitHub Actions!"

      - name: 현재 시간
        run: date

      - name: 환경 정보
        run: |
          echo "OS: $RUNNER_OS"
          echo "워크스페이스: $GITHUB_WORKSPACE"
          echo "커밋: $GITHUB_SHA"